apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: go-server
spec:
  selector:
    matchLabels:
      app: go-server
  replicas: 1
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
        - name: go-server
          image: ferz1ka/hello-go-multi:v5

          livenessProbe:
            httpGet:
              path: /liveness
              port: 80 # container port!
            periodSeconds: 5
            failureThreshold: 1
            successThreshold: 1
            timeoutSeconds: 1 # time in seconds to wait for request before consider a failure

          envFrom:
            - configMapRef:
                name: go-server-configmap-1
            - secretRef:
                name: go-server-secret
          volumeMounts:
            - mountPath: "/app/message"
              name: configmap-volume
      volumes:
        - name: configmap-volume
          configMap:
            name: go-server-configmap-2
            items:
              - key: message
                path: "message.txt"
