apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: go-server
spec:
  selector:
    matchLabels:
      app: go-server
  replicas: 1
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
        - name: go-server
          image: ferz1ka/hello-go-multi:v2
          env:
            - name: NAME
              value: "Ferz1ka"
            - name: VERSION
              value: "v2"
