apiVersion: v1
kind: Service
metadata:
  name: go-server-service
spec:
  selector:
    app: go-server
  type: ClusterIP
  ports:
    - name: go-server-service-port
      port: 8000 # Service port!
      targetPort: 80 # Container port!
      protocol: TCP
